language: python
python:
    
  
  - "2.7"
  
# command to install dependencies
env:
  global:
    PYHTONPATH="/home/travis/build/ogomb/challengeOne/app"
install:
 
  - pip install -r requirements.txt
# command to run tests
script: py.test
